{
 "title": "network",
 "tags": [
  "habruta",
  "network",
  "node-exporter"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Environment",
    "query": {
     "query": "label_values(node_network_receive_bytes_total, env)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(node_network_receive_bytes_total{env=\"$env\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Network In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by (instance) (\n  rate(node_network_receive_bytes_total{\n    env=\"$env\",\n    instance=~\"$instance\",\n    device!~\"lo|docker.*|veth.*|br.*\"\n  }[1m])\n) * 8"
    }
   ]
  },
  {
   "title": "Network Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by (instance) (\n  rate(node_network_transmit_bytes_total{\n    env=\"$env\",\n    instance=~\"$instance\",\n    device!~\"lo|docker.*|veth.*|br.*\"\n  }[1m])\n) * 8"
    }
   ]
  },
  {
   "title": "Network RX Drops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (instance) (\n  rate(node_network_receive_drop_total{\n    env=\"$env\",\n    instance=~\"$instance\",\n    device!~\"lo|docker.*|veth.*|br.*\"\n  }[1m])\n)"
    }
   ]
  },
  {
   "title": "Network TX Drops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (instance) (\n  rate(node_network_transmit_drop_total{\n    env=\"$env\",\n    instance=~\"$instance\",\n    device!~\"lo|docker.*|veth.*|br.*\"\n  }[1m])\n)"
    }
   ]
  },
  {
   "title": "Network RX Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (instance) (\n  rate(node_network_receive_errs_total{\n    env=\"$env\",\n    instance=~\"$instance\",\n    device!~\"lo|docker.*|veth.*|br.*\"\n  }[1m])\n)"
    }
   ]
  },
  {
   "title": "Network TX Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (instance) (\n  rate(node_network_transmit_errs_total{\n    env=\"$env\",\n    instance=~\"$instance\",\n    device!~\"lo|docker.*|veth.*|br.*\"\n  }[1m])\n)"
    }
   ]
  }
 ]
}